### ISSUE TITLE
Adding custom provider endpoints

### ISSUE THREAD

**Issue by pwoo** [adamwathan/eloquent-oauth-l5#20]
Hi @adamwathan,

Loving the relative ease of this package. Works like a charm for authentication. However, I'm having a bit of trouble trying to put together something that can call different endpoints once the access token is retrieved. What I have so far is the following:
- A class that extends OAuth2Provider for the website in question, which defines all of the endpoints and contains the HTTP request logic.
- Another class that extends EloquentOAuthServiceProvider. Its only purpose thus far is to add the new provider to the $providerLookup array.

What I think I need to have done:
- Extend OAuthManager with a method to return the OAuth2Provider. The extended EloquentOAuthServiceProvider must create an object of this class in registerOAuthManager() instead.

Does that sound about right?

Additionally, will calling OAuthManager::login() trigger a new HTTP request if the access token is already stored in the database? 

Thanks.

**Comment by adamwathan** [comment]
I'm having trouble understanding exactly what it is you are trying to do. Are you trying to make additional API calls to the provider after logging in? Like for example if you were using GitHub login but also wanted to get a list of their repositories after the fact?

If so, I would recommend doing that totally separate from what this package offers. Store the access token somewhere on login in the closure, and use a separate API client with that token to do any of that work outside of the whole auth/login side of things.

Re: the last question, yeah `login` will trigger a new HTTP request every time because it uses the data that came back from the redirect to do the login. It needs to use the `code` that comes back, fetch a new access token, make a request to the provider with that access token to get their user details, and then finally check to see if there's already a user in the system matching those details, and if so, log that person in.

**Comment by pwoo** [comment]
Sorry for the confusion. But yes -- I was looking for a way to to make additional API calls after the fact. Thanks for the tips!
