### ISSUE TITLE
Problems SQL

### ISSUE THREAD

**Issue by edisoncosta** [adamwathan/eloquent-oauth-l5#33]
I know it sounds very noob, but I can not perform the authentication routines using Controller.

When you try to login with an account that possesses registered email generates an SQL error.

Thanks,

Success!

**Comment by adamwathan** [comment]
Hi Edison, can you provide the error and the code that created it?

**Comment by edisoncosta** [comment]
Well the code I gave up and I'm using the same route.
But I would leave the controller.

Follows the code in the route:

```
    Route::get('{provider}/login', function ($provider) {
        try {
            SocialAuth::login($provider, function ($user, $userDetails) {
                $user->email = $userDetails->email;
                $user->name = $userDetails->full_name;
                $user->save();
            });
        } catch (ApplicationRejectedException $e) {
            dump($e);

        } catch (InvalidAuthorizationCodeException $e) {
            dump($e);
        }
        return Redirect::intended();
    });

```

Following the error:

`SQLSTATE [23000]: Integrity constraint Violation: Duplicate entry 'edisonpcosta@gmail.com' for key 'users_email_unique' (SQL: insert into`users`(` email`,`name`,` updated_at`,`created_at`) values ( edisonpcosta@gmail.com, Edison Costa, 02.06.2016 16:15:57, 02.06.2016 16:15:57`))

Sorry English, not mastered the language.

Thanks,

**Comment by adamwathan** [comment]
Hi @edisoncosta, are you perhaps trying to login using two different social accounts that share the same email? Perhaps a Facebook account and a GitHub account that both have the same email? It looks like you already have one entry in your database for `edisonpcosta@gmail.com` and it is failing because it is trying to add another user with the same email.

**Comment by edisoncosta** [comment]
Hi @adamwathan, actually the situation is this. Email this field as unique, just to avoid duplicate accounts. How do I avoid this situação.com the SocialAuth.
Thank you.

**Comment by adamwathan** [comment]
Basically 2 options:
1. Don't make it unique, so if someone signs up with Facebook, then with GitHub, they get two separate accounts. This is the easiest solution and how a lot of other sites works.
2. Manually match the user based on their email address in the closure. You can override which user gets used this way, I have an example here: https://github.com/adamwathan/eloquent-oauth-l5/issues/10#issuecomment-172864961

The problem with option 2 is there's a bit of a security risk, because you are assuming that just because the email addresses are the same that it is the same person. If you sign up for a Facebook account using your email, there is nothing to stop me from signing up with a GitHub account using your email, and then logging in to your app with GitHub and getting access to your existing account, because most of these services don't force email verification before letting you use their API.

**Comment by adamwathan** [comment]
Closing for now since not actually a problem with the package but happy to keep discussing it with you here :+1:

**Comment by edisoncosta** [comment]
Thank you for disposal.
Success and congratulations on the package.
