### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by AntyRace** [adamwathan/eloquent-oauth-l5#39]
Hi,
Any chance for twitter auth ?

Regards
Anty

**Comment by adamwathan** [comment]
Hey Anty, yeah would love to get it in some time, only issue is they use OAuth 1 rather than OAuth 2, so it's not as simple as adding another OAuth 2 provider. Would happily accept a PR as a starting point.

Here's another issue on the main repo: https://github.com/adamwathan/eloquent-oauth/issues/3
