### ISSUE TITLE
There is assumption that project works with Illuminate\Database\Eloquent\Model in OAuthIdentity.php

### ISSUE THREAD

**Issue by mvladk** [adamwathan/eloquent-oauth-l5#4]
There is assumption that project works with Illuminate\Database\Eloquent\Model in OAuthIdentity.php
Question:
Is there injection point or a way to override/replace it? 
The only way I see is to fork and replace.

**Comment by adamwathan** [comment]
What is it that you are trying to do? The package is meant specifically for integration with Eloquent and Laravel's Auth system, and the OAuthIdentity class is essentially private to the package and doesn't need to be used by the end user.

**Comment by mvladk** [comment]
My project works with Jenssegers\Mongodb\Model and Mongodb connection without Mysql DB
Currently it works fine with Laravel's Auth system. And fail on class OAuthIdentity extends Eloquent

**Comment by adamwathan** [comment]
Gotcha! Lemme look into it, see if I can figure out a simple solution.

**Comment by adamwathan** [comment]
Looks like the easiest solution without changing anything would be to write your own IdentityStore implementation that looks things up in Mongo, and bootstrap everything in your own service provider instead of using the one that ships with the package.

There's no way to allow changing the base class at runtime so writing your own IdentityStory is really the only option regardless. I will see what I can do about making it easier to override that without writing your own service provider though. Likely will stick an interface in front of it and resolve it out of the IOC in my own service provider, so you can override the interface binding after the fact and use your own implementation. That sound like it would work for you?

**Comment by mvladk** [comment]
Fine. 
That what I thought, Just a wanted to be sure and notify you.
Thank you.

**Comment by mvladk** [comment]
Fine. 
That what I thought, Just a wanted to be sure.
Thank you.

**Comment by adamwathan** [comment]
https://github.com/adamwathan/eloquent-oauth-l5/releases/tag/v0.2.0

Should be able to swap out the IdentityStore now by registering your own IOC binding for it.

**Comment by mvladk** [comment]
Woha! It was fast :)

**Comment by adamwathan** [comment]
If I didn't do it right away it'd take me months :)
