### ISSUE TITLE
Support Laravel 5.3

### ISSUE THREAD

**Issue by shaljam** [adamwathan/eloquent-oauth-l5#49]
changing `InstallCommand` line 21 to
`if (starts_with(app()->version(), '5.1')) {
            $this->composer = app(Composer51::class);
        } else {
            $this->composer = app(Composer52::class);
        }`
seems to help.

**Comment by adamwathan** [comment]
Are you using version 0.5.1? It _should_ work with Laravel 5.3 already, as I've switched that version checking code to just look to find that silly Composer class based on existence rather than Laravel version:

https://github.com/adamwathan/eloquent-oauth-l5/blob/master/src/Installation/InstallCommand.php#L21-L25

**Comment by shaljam** [comment]
No, that was an old installation I updated. It's ^4.2. How should I tell composer to get latest version without editing composer.json?

**Comment by adamwathan** [comment]
Change your composer.json to say `^0.5.1` and run `composer update`.

**Comment by shaljam** [comment]
Thank you.
