### ISSUE TITLE
5.1 - Sqlite

### ISSUE THREAD

**Issue by jrean** [adamwathan/eloquent-oauth-l5#7]
Hi,

I followed the documentation and I'm stuck with the following:

```
SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: users.name (SQL: insert into "users" ("updated_at", "created_at") values (2015-06-27 17:23:57, 2015-06-27 17:23:57))
```

I tried with the Facebook provider. the authorise method is working, I authorise the App then I'm redirected back as expected...

*I have renamed the Alias to `Social` (regarding the last issue)

```
    public function facebookLogin()
    {
        try {
            \Social::login('facebook');

        } catch (ApplicationRejectedException $e) {

        } catch (InvalidAuthorizationCodeException $e) {

        }

        // Current user is now available via Auth facade
        $user = Auth::user();

        dd($user);

    }
```

Did I miss something?

Thank you :)

**Comment by adamwathan** [comment]
Yeah I need to add a section to the documentation :)

The package doesn't automatically insert data into those columns or anything, so you need to set a name for the user in the callback, or make the column nullable if you don't want to save the name for accounts created from social logins.

By default the package will attempt to save a user with no fields to the users table, so your table has to support that or you need to set the fields you need in the login callback.

—
Adam

**Comment by jrean** [comment]
Thank you for you quick answer!
So in fact it is not working "out of the box" with the default L5 user structure?

I have to manually hydrate the user model within the callback or modify the user migration to make "nullable" the name ; email ; password columns? Right?
In your video you do not show this part. You just authorise, login and "boom" you have a new record within 'users' with empty name, email and password.

Fantastic work by the way :)

**Comment by adamwathan** [comment]
Yeah you're right! In the video I was using MySQL which happily uses an empty string by default for non-nullable columns. This is crappy behaviour and MySQL is regularly ridiculed for it :) but it kept the video a bit shorter!

I hope to update the docs this weekend with a section on designing your users table.

—
Adam

**Comment by jrean** [comment]
I made it work no pb :)

Your doc is already pretty much descriptive and complete.

I have 3 extra questions:
- The token you provide and store is a short lived or long lived?
- If I want to take advantage of the `remember_token`, I also need to set it within the callback right?
- What is going on if I login once with Facebook and after with Google for instance and for both I have the same email address? (I didn't try) You will have only one user that can have many oauth_identities?

@adamwathan and finally two more :)

```
            \Social::login('facebook', function($user, $details) {
                $user->name  = $details->nickname;
                $user->email = $details->email;
            });
```
- I didn't have to `$user->save()` It saved itself! Is that the normal behaviour?

Right after that I `dd(\Auth::check()); // true`. So we have an authenticated user.
If I hit another route, for instance `/foo/bar` and run `dd(\Auth::check); // false`. 
- Why it is not stored in the session? Did I miss something? (related to my second question, how can I take advantage of the `remember_me`?

Thank you.

**Comment by jrean** [comment]
Update...
If we want the authenticated user to be stored in session we MUST return a redirect() and only at this time the authenticated user will be stored in session and accessible anywhere with `\Auth::user()` and testable with `\Auth::check()`. I had a hard tim to figure it out.

**Comment by adamwathan** [comment]
@jrean Answer to your questions!

> The token you provide and store is a short lived or long lived?

This depends entirely on the provider. GitHub tokens never expire for example, while Facebook tokens are always short lived until you request a long lived token as a secondary action. I don't go out of my way to request long lived tokens for anything.

I'm actually intending to stop storing access tokens as part of the package behavior, because they are never used again by the package. I'll still make them available in the login callback so users of the package can decide to store it elsewhere if they want to re-use it though.

> If I want to take advantage of the `remember_token`, I also need to set it within the callback right?

I haven't experimented with this much personally. I remember having good reasons for not support `remember_me` stuff out of the box, but I can't remember what they were now :blush: I think it was something to do with worrying about access tokens expiring, but now that I know more about it that's not a problem.

I'll probably expose another method like `loginForever` that does remember me. In the past, I've just not worried about it for social login because it's one click to login if the person closes their browser and gets logged out.

> What is going on if I login once with Facebook and after with Google for instance and for both I have the same email address? (I didn't try) You will have only one user that can have many oauth_identities?

Two different users will be created. Treating two third party users as the same user based on email is a security vulnerability. Other people have asked about this in the past, you can read more here: https://github.com/adamwathan/eloquent-oauth/issues/19#issuecomment-57561353

Supporting social login with multiple providers has some usability trade-offs (_did I login with Google or did I login with Facebook? I can't remember!_) so you just have to weigh the issues there against the benefits for your particular app. Personally I try to just use one provider so avoid that confusion, as well as avoid the need for building out functionality to merge accounts, because it's very app-specific and can get quite complicated.

> I didn't have to $user->save() It saved itself! Is that the normal behaviour?

Yeah the `$user` will be saved afterwards by the package no matter what (for other reasons), so you don't really _need_ to save in the callback. I might be implementing some more complex features down the road which will require you to return the user from callback, but that'll definitely get updated in the documentation if/when it happens.

> Why it is not stored in the session? Did I miss something?

Hmm this shouldn't be happening, are other session related things working correctly? The package literally just calls `Auth::login(...)` once it has the correct user, so it doesn't interact with the session directly. If a normal login persists, so should social logins.

> If we want the authenticated user to be stored in session we MUST return a redirect() and only at this time the authenticated user will be stored in session and accessible anywhere with \Auth::user() and testable with \Auth::check(). I had a hard tim to figure it out.

I suspect it was some other issue because there's no way for the package to know what response you are returning from the route after the fact. So if you just returned a view, the login wouldn't persist across to the next page? I wonder if this is how the regular auth stuff works? Seems unusual to me.

**Comment by jrean** [comment]
@adamwathan thank you so much for this very detailed answer! Brilliant.

> I'm actually intending to stop storing access tokens as part of the package behaviour, because they are never used again by the package. I'll still make them available in the login callback so users of the package can decide to store it elsewhere if they want to re-use it though.

I'll keep an eye on it so. I'm building a medium web app on top of your package right now, so I will pay attention to the next updates.

> I suspect it was some other issue because there's no way for the package to know what response you are returning from the route after the fact. So if you just returned a view, the login wouldn't persist across to the next page? I wonder if this is how the regular auth stuff works? Seems unusual to me.

I discovered that when you `\Auth::login()` or `\Auth::attempt()` you have to return a `response` or a `redirect` (which is a response) and only at this time the user will be store in session and so available to the next request. I had a very hard time when trying for the first time the package because I was `dd()` before (and prior) returning any response. Anyway, it's working like a charm.

I'm kind very interested by your work and quite fan about "login flows". So if you feel you need some help for the package, even for documentation or anything feel free to open your doors :)

Last question:

From Facebook `https://developers.facebook.com/docs/facebook-login/permissions/v2.3`:

> Note, even if you request the email permission it is not guaranteed you will get an email address. For example, if someone signed up for Facebook with a phone number instead of an email address, the email field may be empty.

So that means this is possible (even) with Facebook the email won't be available. I was wondering the following:
I implemented in my code the following because I don't know why you return if there is no email:

```
                if (property_exists($details, 'email')) {
                    ...
                }
```

Do you return the email property in any case? If no email `$details->email` will be equal to `null`.

Thank you again :)

**Comment by adamwathan** [comment]
Yeah the email property will be null if it doesn't come back from Facebook. It's always null for Instagram and Soundcloud too as they don't provide you an email no matter what :+1:

**Comment by jrean** [comment]
@adamwathan while working with the package I'm wondering the following:

Don't you think it could be useful if the $user instance you give access within the callback would have already been persisted (once) the very first time a user login?

The very first time `$user->id` is null.

```
        try {
            \Social::login('facebook', function($user, $details) {

                dump($user->id); // null
                $user->save();
                dump($user->id); // 1
```

Then the second and n time:

```
try {
            \Social::login('facebook', function($user, $details) {

                dump($user->id); // 1
```

In my case it could be useful because for each login I `firstOrNew(['user_id' => $user->id])` a `UserProfile` model and it could avoid to use a `$user->save()` before to get the `$user->id` value.

What do you think about it?

**Comment by adamwathan** [comment]
Yeah it actually _used_ to work that way, but I did some refactoring so that it didn't save until after the callback. There were 2 reasons for this:
1. Most importantly, if someone has non-nullable/non-default columns on their `users` table, saving the user before the callback will result in database exception because those fields will be missing and the package has no way of determining what data it should provide there. For example, if you want to save the user's avatar URL and you have a non-nullable column for that on your users table, you need to assign that property to the user before it saves the first time. If I make the package save without letting the end user assign that field first, everything will blow up :) https://github.com/adamwathan/eloquent-oauth/commit/916cac7e2082e336142c86421058b77d5064098a
2. I wanted to introduce a point where people could throw an exception and abort the login process without creating the user at all if they needed to do any custom checking inside of the callback.

**Comment by jrean** [comment]
That make sense!
But nevertheless I had to make my `User` columns nullable because I was using `sqlite` :p

**Comment by adamwathan** [comment]
Haha, yes well you need to make sure you either set the right fields in the callback or design your `users` table so that it new users can be created with no info. Making the columns nullable is one way to do that, not having those columns at all is another :)

**Comment by jrean** [comment]
Don't you think it is almost impossible to avoid `nullable` for the email column?
Because even Facebook can return a `null` email and sqlite won't accept a empty value...
So yes I could check and hydrate a faked "default" email but this seems crazy. It better to make the email column nullable I guess? (It's what I did)

**Comment by adamwathan** [comment]
Yeah I think if you want to have an email column and support Facebook login, it needs to be nullable. You could always ask for their email as the next step in the login/signup flow manually, seen a few sites do that. Column still needs to be nullable though.

If you were only supporting Google or GitHub you'd be ok (maybe LinkedIn too, can't remember), but all other providers could screw you.

**Comment by jrean** [comment]
It is what I did :-)
But now I try to manage the following, what if a user logged in the first time with Facebook and Facebook gave no email (it could happen), so in the next step I ask for email and update the `User` table.. But the second time the user log in with Facebook but this time Facebook give an email.. (This sounds crazy but it could happen).. Within the closure it will override the existing email. The question is which email to keep. The one provided by the user on "step" 2 or the new one provided (by the user) trough Facebook...
Hum.

**Comment by adamwathan** [comment]
Yeah definitely gets more complicated. If I were you I would probably somehow keep track of whether or not an email was set manually and only update on subsequent logins if it was set automatically and you want to keep it synchronized with the Facebook email. Definitely out of the scope of this package though :/

**Comment by jrean** [comment]
Yes sorry. You can close the "issue", I already abused way too much of the "out of scope" concept :/
Thank you

**Comment by adamwathan** [comment]
Hahaha, no problem, good luck with your project and feel free to ping me with any issues or questions :)
